function result = runBentheimerPhreeqcEquilibrium(varargin)
% Equilibrate the H2Storage1D Bentheimer brine with its mineral inventory.
%
% Requires PhreeqcMatlab to have been initialized with startup_Phreeqc.
% UGFACT's PITZER_Modified.DAT requires its custom IPhreeqcCOM build and
% cannot be loaded by PhreeqcMatlab's standard PHREEQC library.

opt = struct(...
    'databaseFile', '', ...
    'ugfactCompatible', false, ...
    'dolomitePhase', 'Dolomite', ...
    'calcitePhase', 'Calcite', ...
    'brucitePhase', 'Brucite', ...
    'quartzPhase', 'Quartz', ...
    'porosity', 0.20, ...
    'waterSaturation', 0.5508, ...
    'cellVolume', 50, ...
    'waterDensity', 1000, ...
    'pH', 6.24, ...
    'temperature', 60, ...
    'Na', 2.865, ...
    'Ca', 0.2857, ...
    'Mg', 0.1144, ...
    'Cl', 3.655, ...
    'SO4', 4.664e-3, ...
    'C4', 1.370e-3, ...
    'Si', 9.723e-5, ...
    'dolomiteWtFraction', 0.02, ...
    'calciteWtFraction', 0, ...
    'bruciteWtFraction', 0, ...
    'quartzWtFraction', 0.98);
opt = merge_options(opt, varargin{:});

assert(exist('IPhreeqc', 'file') == 2, ...
    'Run startup_Phreeqc before calling runBentheimerPhreeqcEquilibrium.');
assert(opt.dolomiteWtFraction + opt.calciteWtFraction + ...
    opt.bruciteWtFraction + opt.quartzWtFraction <= 1, ...
    'Mineral weight fractions must sum to no more than one.');
fractions = [opt.dolomiteWtFraction, opt.calciteWtFraction, ...
    opt.bruciteWtFraction, opt.quartzWtFraction];
assert(all(isfinite(fractions) & fractions >= 0) && sum(fractions) > 0, ...
    'Mineral weight fractions must be finite, non-negative, and nonzero.');
assert(opt.waterSaturation > 0 && opt.porosity > 0, ...
    'waterSaturation and porosity must be positive.');

if isempty(opt.databaseFile)
    assert(exist('database_file', 'file') == 2, ...
        'Provide databaseFile or run startup_Phreeqc first.');
    opt.databaseFile = database_file('pitzer.dat');
end
assert(isfile(opt.databaseFile), 'PHREEQC database not found: %s', opt.databaseFile);
databaseName = lower(string(opt.databaseFile));
assert(contains(databaseName, 'pitzer') && ...
    ~contains(databaseName, 'pitzer_modified') && ~contains(databaseName, 'ugfact'), ...
    'Bentheimer PHREEQC initialization requires the standard PHREEQC pitzer.dat database.');
assert(~opt.ugfactCompatible, ...
    ['UGFACT''s PITZER_Modified.DAT uses pseudo-elements that PhreeqcMatlab ', ...
     'cannot parse. Use a standard Pitzer database with this utility.']);

carbonComponent = 'C(4)';
sulfateComponent = 'S(6)';
co2Species = 'CO2';
hco3Species = 'HCO3-';
co3Species = 'CO3-2';
sulfateSpecies = 'SO4-2';

% The unit-cell volume is one cubic metre in H2Storage1D. Retain both the
% rock mineral inventories in moles (for EQUILIBRIUM_PHASES) and their
% water-normalized values (for initializing MRST's per-cell inventory).
rhoRock = 1/(opt.quartzWtFraction/2650 + opt.dolomiteWtFraction/2840 + ...
    opt.calciteWtFraction/2710 + opt.bruciteWtFraction/2390);
rockMass = (1 - opt.porosity)*opt.cellVolume*rhoRock;
waterMass = opt.porosity*opt.cellVolume*opt.waterSaturation*opt.waterDensity;
dolomiteMoles = opt.dolomiteWtFraction*rockMass/0.18440;
calciteMoles = opt.calciteWtFraction*rockMass/0.1000869;
bruciteMoles = opt.bruciteWtFraction*rockMass/0.0583197;
quartzMoles = opt.quartzWtFraction/0.060083*rockMass;
dolomiteMolality = dolomiteMoles/waterMass;
calciteMolality = calciteMoles/waterMass;
bruciteMolality = bruciteMoles/waterMass;
quartzMolality = quartzMoles/waterMass;

input = sprintf([ ...
    'SELECTED_OUTPUT 1\n' ...
    '    -reset false\n' ...
    '    -pH true\n' ...
    '    -totals %s %s Na Ca Mg Cl Si\n' ...
    '    -molalities %s %s %s %s\n' ...
    '    -equilibrium_phases %s %s %s %s\n' ...
    'END\n' ...
    'SOLUTION 1 Bentheimer\n' ...
    '    units mol/kgw\n' ...
    '    -water %.15g\n' ...
    '    temp %.15g\n' ...
    '    pH %.15g\n' ...
    '    Na %.15g\n' ...
    '    Ca %.15g\n' ...
    '    Mg %.15g\n' ...
    '    Cl %.15g\n' ...
    '    %s %.15g as SO4\n' ...
    '    %s %.15g as HCO3\n' ...
    '    Si %.15g\n' ...
    'END\n' ...
    'EQUILIBRIUM_PHASES 1\n' ...
    '    %s 0 %.15g\n' ...
    '    %s 0 %.15g\n' ...
    '    %s 0 %.15g\n' ...
    '    %s 0 %.15g\n' ...
    'END\n' ...
    'USE solution 1\n' ...
    'USE equilibrium_phases 1\n' ...
    'END\n'], ...
    carbonComponent, sulfateComponent, co2Species, hco3Species, co3Species, sulfateSpecies, ...
    opt.dolomitePhase, opt.calcitePhase, opt.brucitePhase, opt.quartzPhase, ...
    waterMass, opt.temperature, opt.pH, opt.Na, opt.Ca, opt.Mg, opt.Cl, ...
    sulfateComponent, opt.SO4, carbonComponent, opt.C4, opt.Si, ...
    opt.dolomitePhase, dolomiteMoles, ...
    opt.calcitePhase, calciteMoles, ...
    opt.brucitePhase, bruciteMoles, ...
    opt.quartzPhase, quartzMoles);

iph = IPhreeqc();
iph = iph.CreateIPhreeqc();
cleanup = onCleanup(@() iph.DestroyIPhreeqc());

status = iph.LoadDatabase(opt.databaseFile);
assert(status == 0, 'PHREEQC could not load database: %s', opt.databaseFile);
iph.SetOutputStringOn(1);
iph.SetSelectedOutputStringOn(1);
status = iph.RunString(input);
assert(status == 0, 'PHREEQC equilibrium calculation failed:\n%s', iph.GetErrorString());

selectedOutput = iph.GetSelectedOutputString();
[headers, values] = parseSelectedOutput(selectedOutput);
assert(~isempty(values), 'PHREEQC produced no selected-output data rows.');
finalValues = values(end, :);

result = struct(...
    'input', input, ...
    'output', iph.GetOutputString(), ...
    'selectedOutput', selectedOutput, ...
    'selectedOutputHeaders', {headers}, ...
    'selectedOutputValues', values, ...
    'aqueous', struct(...
        'pH', getSelectedValue(headers, finalValues, 'pH'), ...
        'totalCarbon', getSelectedValue(headers, finalValues, 'C_4_'), ...
        'sulfate', getSelectedValue(headers, finalValues, 'S_6_'), ...
        'ca', getSelectedValue(headers, finalValues, 'Ca'), ...
        'mg', getSelectedValue(headers, finalValues, 'Mg'), ...
        'co2', getSelectedValue(headers, finalValues, 'm_CO2'), ...
        'hco3', getSelectedValue(headers, finalValues, 'm_HCO3_'), ...
        'co3', getSelectedValue(headers, finalValues, 'm_CO3_2'), ...
        'so4', getSelectedValue(headers, finalValues, 'm_SO4_2')), ...
    'minerals', struct(...
        'dolomite', getSelectedValue(headers, finalValues, ...
            matlab.lang.makeValidName(opt.dolomitePhase)), ...
        'calcite', getSelectedValue(headers, finalValues, ...
            matlab.lang.makeValidName(opt.calcitePhase)), ...
        'brucite', getSelectedValue(headers, finalValues, ...
            matlab.lang.makeValidName(opt.brucitePhase)), ...
        'quartz', getSelectedValue(headers, finalValues, ...
            matlab.lang.makeValidName(opt.quartzPhase))), ...
    'databaseFile', opt.databaseFile, ...
    'dolomiteMoles', dolomiteMoles, ...
    'calciteMoles', calciteMoles, ...
    'bruciteMoles', bruciteMoles, ...
    'quartzMoles', quartzMoles, ...
    'dolomiteMolality', dolomiteMolality, ...
    'calciteMolality', calciteMolality, ...
    'bruciteMolality', bruciteMolality, ...
    'quartzMolality', quartzMolality, ...
    'waterMass', waterMass, ...
    'rockMass', rockMass);
end

function [headers, values] = parseSelectedOutput(selectedOutput)
lines = splitlines(string(selectedOutput));
lines = strtrim(lines(strlength(strtrim(lines)) > 0));
assert(numel(lines) >= 2, 'PHREEQC selected output contains no data rows.');

headers = regexp(char(lines(1)), '\s+', 'split');
headers = cellfun(@matlab.lang.makeValidName, headers, 'UniformOutput', false);
values = zeros(numel(lines) - 1, numel(headers));
for i = 2:numel(lines)
    row = sscanf(char(lines(i)), '%f').';
    assert(numel(row) == numel(headers), ...
        'Could not parse PHREEQC selected-output row %d.', i - 1);
    values(i - 1, :) = row;
end
end

function value = getSelectedValue(headers, values, name)
ix = find(strcmp(headers, name), 1);
assert(~isempty(ix), 'PHREEQC selected output is missing column %s.', name);
value = values(ix);
end
