function state = runH2StorageUgfactIPhreeqcCOMTimestepCoupling(model, state, dt)
% Run the optional UGFACT PHREEQC_Modified.DAT split after convergence.
%
% This backend intentionally follows the UGFACT IPhreeqcCOM input and
% SELECTED_OUTPUT convention. It is Windows-only: PHREEQC owns MET/ACE/SRB
% kinetics and its biomass state, while MRST retains flow and tracer
% transport. It is a sequential split, not a claim of exact reproduction
% of any external benchmark or publication.

assert(model.phreeqcTimestepCoupling && model.isUgfactComPhreeqcBackend(), ...
    'UGFACT IPhreeqcCOM timestep coupling is not enabled on this model.');
assert(ispc, ['UGFACT IPhreeqcCOM timestep coupling is available only on ', ...
    'Windows with a registered IPhreeqcCOM server.']);
validateattributes(dt, {'numeric'}, {'scalar', 'real', 'finite', 'positive'}, ...
    mfilename, 'dt');

opt = getCouplingOptions(model);
validateCouplingOptions(opt);
assert(exist('actxserver', 'file') == 2 || exist('actxserver', 'builtin') == 5, ...
    ['IPhreeqcCOM activation is unavailable. Install/register the Windows ', ...
     'IPhreeqcCOM server identified by phreeqcComProgId.']);

nc = model.G.cells.num;
rhoWater = opt.waterDensity;
waterMass = getWaterMass(model, state, rhoWater);
assert(all(isfinite(waterMass) & waterMass > 0), ...
    'UGFACT PHREEQC coupling requires positive liquid water mass in every cell.');

state = initializeUgfactState(state, opt, nc);
state = applyUgfactFirstStepBiomassConvention(state, waterMass);
phase = getPhaseData(model, state, waterMass, rhoWater);
mineral = getMineralData(state, waterMass, nc);
state = storePhreeqcInputDiagnostics(state, phase);

results = repmat(emptyResult(), nc, 1);
for cellNo = 1:nc
    input = buildPhreeqcInput(opt, phase, mineral, state, cellNo, dt);
    if cellNo == 1
        state.phreeqcUgfactInputCell1String = input;
    end
    output = runIPhreeqcCOM(input, opt, cellNo);
    results(cellNo) = parseSelectedOutput(output, cellNo);
end

state = updateStateFromResults(model, state, opt, phase, mineral, results, waterMass, dt);
end

function state = storePhreeqcInputDiagnostics(state, phase)
% Retain the exact mol/kg-water PHREEQC basis for comparison with UGFACT.
state.phreeqcUgfactInputWaterMass = phase.waterMass;
state.phreeqcUgfactInputH2Moles = phase.gasH2;
state.phreeqcUgfactInputCO2Moles = phase.gasCO2;
state.phreeqcUgfactInputCH4Moles = phase.gasCH4;
state.phreeqcUgfactInputH2SMoles = phase.gasH2S;
state.phreeqcUgfactInputGasVolumeLPerKg = phase.gasVolumeLPerKg;
state.phreeqcUgfactInputPH = phase.pH;
state.phreeqcUgfactInputC4 = phase.C4;
state.phreeqcUgfactInputS6 = phase.S6;
state.phreeqcUgfactInputCa = phase.Ca;
state.phreeqcUgfactInputMg = phase.Mg;
state.phreeqcUgfactInputActiveCells = phase.activeCells;
end

function opt = getCouplingOptions(model)
opt = struct( ...
    'databaseFile', model.phreeqcDatabaseFile, ...
    'comProgId', model.phreeqcComProgId, ...
    'waterDensity', 1000, ...
    'Na', 2.865, ...
    'K', 0, ...
    'Ca', 0.2857, ...
    'Mg', 0.1144, ...
    'Cl', 3.655, ...
    'Si', 9.723e-5, ...
    'Fe3', 0, ...
    'Fe2', 0, ...
    'ugfactSteps', 3, ...
    'ugfactMuMET', 1.109, ...
    'ugfactMuACE', 0.872, ...
    'ugfactMuSRB', 1.048, ...
    'ugfactBMET', 0.01109, ...
    'ugfactBACE', 0.00872, ...
    'ugfactBSRB', 0.01048, ...
    'ugfactYMET', 0.03*4, ...
    'ugfactYACE', 0.07*4, ...
    'ugfactYSRB', 0.08*4, ...
    'ugfactKDMET', 10e-6, ...
    'ugfactKDACE', 2.5e-6, ...
    'ugfactKDSRB', 2.9e-6, ...
    'ugfactKAMET', 230e-6, ...
    'ugfactKAACE', 115.5e-6, ...
    'ugfactKASRB', 2751.5e-6, ...
    'ugfactN0', 1e9, ...
    'ugfactNmax', 1e13, ...
    'ugfactCellMass', 1e-14, ...
    'ugfactBiomassMW', 24.6);

configured = model.phreeqcCouplingOptions;
names = fieldnames(opt);
for i = 1:numel(names)
    name = names{i};
    if isfield(configured, name)
        opt.(name) = configured.(name);
    end
end
end

function validateCouplingOptions(opt)
assert(ischar(opt.databaseFile) || ...
    (isstring(opt.databaseFile) && isscalar(opt.databaseFile)), ...
    'ugfact-com databaseFile must be a character vector or scalar string.');
opt.databaseFile = char(opt.databaseFile); %#ok<NASGU>
assert(~isempty(strtrim(opt.databaseFile)) && isAbsolutePath(opt.databaseFile), ...
    ['ugfact-com requires an explicit absolute databaseFile path to ', ...
     'PHREEQC_Modified.DAT.']);
assert(isfile(opt.databaseFile), ...
    'UGFACT PHREEQC database not found: %s', opt.databaseFile);
[~, databaseName, extension] = fileparts(opt.databaseFile);
assert(strcmpi(extension, '.dat') && contains(lower(databaseName), 'phreeqc_modified'), ...
    ['ugfact-com requires PHREEQC_Modified.DAT, not a standard PHREEQC ', ...
     'Pitzer database: %s'], opt.databaseFile);
assert(ischar(opt.comProgId) || (isstring(opt.comProgId) && isscalar(opt.comProgId)), ...
    'ugfact-com comProgId must identify a registered IPhreeqcCOM server.');
assert(~isempty(strtrim(char(opt.comProgId))), ...
    'ugfact-com comProgId must identify a registered IPhreeqcCOM server.');
validateattributes(opt.waterDensity, {'numeric'}, {'scalar', 'real', 'finite', 'positive'});
validateattributes(opt.ugfactSteps, {'numeric'}, ...
    {'scalar', 'integer', 'finite', 'positive'});

positive = {'ugfactMuMET', 'ugfactMuACE', 'ugfactMuSRB', ...
    'ugfactYMET', 'ugfactYACE', 'ugfactYSRB', ...
    'ugfactKDMET', 'ugfactKDACE', 'ugfactKDSRB', ...
    'ugfactKAMET', 'ugfactKAACE', 'ugfactKASRB', ...
    'ugfactN0', 'ugfactNmax', 'ugfactCellMass', 'ugfactBiomassMW'};
for i = 1:numel(positive)
    validateattributes(opt.(positive{i}), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'positive'}, mfilename, positive{i});
end
nonnegative = {'ugfactBMET', 'ugfactBACE', 'ugfactBSRB', ...
    'Na', 'K', 'Ca', 'Mg', 'Cl', 'Si', 'Fe3', 'Fe2'};
for i = 1:numel(nonnegative)
    validateattributes(opt.(nonnegative{i}), {'numeric'}, ...
        {'scalar', 'real', 'finite', 'nonnegative'}, mfilename, nonnegative{i});
end
assert(opt.ugfactNmax >= opt.ugfactN0, ...
    'ugfactNmax must be at least ugfactN0.');
end

function state = initializeUgfactState(state, opt, nc)
% Stored biomass is mol/kg water and never aliases MRST's nbact field.
initialBiomass = opt.ugfactN0*opt.ugfactCellMass/opt.ugfactBiomassMW;
biomassFields = {'phreeqcUgfactBiomassMET', 'phreeqcUgfactBiomassACE', ...
    'phreeqcUgfactBiomassSRB'};
for i = 1:numel(biomassFields)
    field = biomassFields{i};
    if isfield(state, field)
        values = asCellVector(value(state.(field)), nc, field);
        assert(all(isfinite(values) & values >= 0), ...
            '%s must be finite and non-negative.', field);
        state.(field) = values;
    else
        state.(field) = repmat(initialBiomass, nc, 1);
    end
end

mineralFields = {'phreeqcMineralCalcite', 'phreeqcMineralDolomite', ...
    'phreeqcMineralAnhydrite', 'phreeqcMineralQuartz', ...
    'phreeqcMineralGoethite', 'phreeqcMineralBrucite', ...
    'phreeqcMineralPortlandite', 'phreeqcMineralPyrite', ...
    'phreeqcMineralGypsum'};
for i = 1:numel(mineralFields)
    field = mineralFields{i};
    if ~isfield(state, field)
        state.(field) = zeros(nc, 1);
    end
end
end

function state = applyUgfactFirstStepBiomassConvention(state, waterMass)
% H2Storage1D initializes Solution.*_Biomass in mol/kgw, but its first
% buildPhreeqcStrings call divides those values by cell water mass as if
% they were mol/cell. Subsequent calls use PHREEQC output stored in
% mol/cell and are unit-consistent. Preserve this reference convention so
% the ugfact-com adapter reproduces the published workflow exactly.
flag = 'phreeqcUgfactFirstStepBiomassConventionApplied';
if isfield(state, flag) && state.(flag)
    return;
end
fields = {'phreeqcUgfactBiomassMET', 'phreeqcUgfactBiomassACE', ...
    'phreeqcUgfactBiomassSRB'};
for i = 1:numel(fields)
    field = fields{i};
    state.(field) = state.(field)./waterMass;
end
state.(flag) = true;
end

function phase = getPhaseData(model, state, waterMass, rhoWater)
nc = model.G.cells.num;
phase = struct();
phase.waterMass = waterMass;
phase.temperature = asCellVector(value(state.T), nc, 'temperature');
phase.pressureAtm = asCellVector(value(state.pressure)./101325, nc, 'pressure');
phase.pH = getStateVector(state, 'phreeqcPH', nc, model.carbonateBufferPH);
phase.Na = optionVector(model.phreeqcCouplingOptions, 'Na', 2.865, nc);
phase.K = optionVector(model.phreeqcCouplingOptions, 'K', 0, nc);
phase.Cl = optionVector(model.phreeqcCouplingOptions, 'Cl', 3.655, nc);
phase.Si = optionVector(model.phreeqcCouplingOptions, 'Si', 9.723e-5, nc);
phase.Fe3 = optionVector(model.phreeqcCouplingOptions, 'Fe3', 0, nc);
phase.Fe2 = optionVector(model.phreeqcCouplingOptions, 'Fe2', 0, nc);
phase.Ca = max(getStateVector(state, 'tracerCa', nc, 0)./rhoWater, 0);
phase.Mg = max(getStateVector(state, 'tracerMg', nc, 0)./rhoWater, 0);
phase.S6 = max(getStateVector(state, 'tracerSO4', nc, 0)./rhoWater, 0);
phase.S2 = max(getStateVector(state, 'tracerHS', nc, 0)./rhoWater, 0);

componentMoles = getEOSComponentMoles(model, state);
phase.componentMoles = componentMoles;
[phase.rhoL, phase.rhoV, phase.sL, phase.sV] = getPhaseProperties(model, state);
poreVolume = asCellVector(value(model.PVTPropertyFunctions.get( ...
    model, state, 'PoreVolume')), nc, 'pore volume');
phase.gasVolumeLPerKg = max(poreVolume.*phase.sV.*1000./waterMass, 1e-12);
phase.gasVolumeL = max(poreVolume.*phase.sV.*1000, 1e-6);
phase.ZV = asCellVector(value(state.Z_V), nc, 'gas compressibility factor');
phase.gasTemperature = phase.temperature;

names = model.EOSModel.CompositionalMixture.names;
% UGFACT's GAS_PHASE inventory is its total component inventory per kg
% water, rather than only the EOS vapor-phase portion. This gives PHREEQC
% the complete volatile inventory to repartition; supplying only y*Sg
% would silently discard pre-existing dissolved gas at every split.
phase.gasH2 = getComponentMoles(componentMoles, names, {'H2', 'Hydrogen'});
phase.gasCO2 = getComponentMoles(componentMoles, names, {'CO2', 'CarbonDioxide'});
phase.gasCH4 = getComponentMoles(componentMoles, names, {'C1', 'CH4', 'Methane'});
phase.gasH2S = getComponentMoles(componentMoles, names, {'H2S', 'HydrogenSulfide'});
phase.gasN2 = getComponentMoles(componentMoles, names, {'N2', 'Nitrogen'}, false);
components = value(state.components);
% Match UGFACT's component cleanup before the PHREEQC gas inventory is
% constructed.
phase.gasH2 = zeroTraceComponent(phase.gasH2, components, names, {'H2', 'Hydrogen'});
phase.gasCO2 = zeroTraceComponent(phase.gasCO2, components, names, {'CO2', 'CarbonDioxide'});
phase.gasCH4 = zeroTraceComponent(phase.gasCH4, components, names, {'C1', 'CH4', 'Methane'});
phase.gasH2S = zeroTraceComponent(phase.gasH2S, components, names, {'H2S', 'HydrogenSulfide'});
phase.gasN2 = zeroTraceComponent(phase.gasN2, components, names, {'N2', 'Nitrogen'});
phase.totalH2 = phase.gasH2;
iH2 = findComponent(names, {'H2', 'Hydrogen'});
phase.activeCells = components(:, iH2) > 1e-3 & phase.sL >= 1e-3;
phase.partialH2 = gasPartialPressure(phase.gasH2, phase);
phase.partialCO2 = gasPartialPressure(phase.gasCO2, phase);
phase.partialCH4 = gasPartialPressure(phase.gasCH4, phase);
phase.partialH2S = gasPartialPressure(phase.gasH2S, phase);
phase.partialN2 = gasPartialPressure(phase.gasN2, phase);

% tracerHCO3 carries nonvolatile C(4). EOS CO2 is supplied separately in
% GAS_PHASE_MODIFY, exactly as in UGFACT; adding dissolved EOS CO2 here
% would count the same carbon inventory twice.
phase.C4 = max(getStateVector(state, 'tracerHCO3', nc, 0)./rhoWater, 0);
phase.Acetate = max(getStateVector(state, 'phreeqcUgfactAcetate', nc, 0), 0);
end

function mineral = getMineralData(state, waterMass, nc)
mineral = struct();
mineral.calcite = getStateVector(state, 'phreeqcMineralCalcite', nc, 0)./waterMass;
mineral.dolomite = getStateVector(state, 'phreeqcMineralDolomite', nc, 0)./waterMass;
mineral.anhydrite = getStateVector(state, 'phreeqcMineralAnhydrite', nc, 0)./waterMass;
mineral.quartz = getStateVector(state, 'phreeqcMineralQuartz', nc, 0)./waterMass;
mineral.goethite = getStateVector(state, 'phreeqcMineralGoethite', nc, 0)./waterMass;
mineral.brucite = getStateVector(state, 'phreeqcMineralBrucite', nc, 0)./waterMass;
mineral.portlandite = getStateVector(state, 'phreeqcMineralPortlandite', nc, 0)./waterMass;
mineral.pyrite = getStateVector(state, 'phreeqcMineralPyrite', nc, 0)./waterMass;
mineral.gypsum = getStateVector(state, 'phreeqcMineralGypsum', nc, 0)./waterMass;
end

function input = buildPhreeqcInput(opt, phase, mineral, state, cellNo, dt)
biomassMET = state.phreeqcUgfactBiomassMET(cellNo);
biomassACE = state.phreeqcUgfactBiomassACE(cellNo);
biomassSRB = state.phreeqcUgfactBiomassSRB(cellNo);
maxBiomass = opt.ugfactNmax*opt.ugfactCellMass/opt.ugfactBiomassMW;
minBiomass = opt.ugfactN0*opt.ugfactCellMass/opt.ugfactBiomassMW;
if phase.activeCells(cellNo)
    h2Available = max(phase.totalH2(cellNo)./phase.waterMass(cellNo), 0);
else
    h2Available = 0;
end

input = sprintf([ ...
    'KNOBS\n' ...
    '-iterations 800\n' ...
    '-step_size 30\n' ...
    '-convergence_tolerance 1e-10\n' ...
    '%s' ...
    'END\n' ...
    'SOLUTION 1\n' ...
    '-pressure %.15g\n' ...
    '-temp %.15g\n' ...
    'pH %.15g #charge\n' ...
    'units mol/kgw\n' ...
    'K %.15g\n' ...
    'Na %.15g\n' ...
    'Mg %.15g\n' ...
    'Ca %.15g\n' ...
    'Cl %.15g\n' ...
    'Carbonate(4) %.15g\n' ...
    'Sulfate(6) %.15g\n' ...
    'Sulfide(-2) %.15g\n' ...
    'Fe_tri %.15g\n' ...
    'Fe_di %.15g\n' ...
    'Si %.15g\n' ...
    'Acetate %.15g\n' ...
    '-water 1\n' ...
    'END\n' ...
    'GAS_PHASE 1\n' ...
    '-pressure %.15g\n' ...
    '-temp %.15g\n' ...
    '-fixed_volume\n' ...
    '-volume %.15g\n' ...
    'H2(g) %.15g\n' ...
    'redoxCarbonateO2(g) %.15g\n' ...
    'redoxCH4(g) %.15g\n' ...
    'redoxH2S(g) %.15g\n' ...
    'N2(g) %.15g\n' ...
    'GAS_PHASE_MODIFY 1\n' ...
    '-type 1\n' ...
    '-total_p %.15g\n' ...
    '-volume %.15g\n' ...
    '-component H2(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxCH4(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxCarbonateO2(g)\n' ...
    '-moles %.15g\n' ...
    '-component redoxH2S(g)\n' ...
    '-moles %.15g\n' ...
    '-component N2(g)\n' ...
    '-moles %.15g\n' ...
    'END\n' ...
    'INCREMENTAL_REACTIONS true\n' ...
    'KINETICS 1\n' ...
    'Biomass_SRB\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'Biomass_MET\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'Biomass_ACE\n' ...
    '-formula H 0\n' ...
    '-M0 %.15g\n' ...
    'MET\n' ...
    '-M %.15g moles\n' ...
    '-formula HCarbonateO3 -0.25 H2 -1 H+ -0.25 MethaneH4 0.25 H2O 0.75\n' ...
    'SRB\n' ...
    '-M %.15g moles\n' ...
    '-formula SulfateO4 -0.25 H2 -1 H+ -0.25 HSulfide 0.25 H2O 1\n' ...
    'ACE\n' ...
    '-M %.15g moles\n' ...
    '-formula HCarbonateO3 -0.5 H2 -1 H+ -0.25 Acetate 0.25 H2O 1\n' ...
    '-step %.15g in %d steps\n' ...
    '-bad_step_max 800\n' ...
    'END\n' ...
    'EQUILIBRIUM_PHASES 1\n' ...
    'redoxCalcite 0 %.15g\n' ...
    'redoxDolomite 0 %.15g\n' ...
    'redoxAnhydrite 0 %.15g\n' ...
    'Quartz 0 %.15g\n' ...
    'redoxGoethite 0 %.15g\n' ...
    'redoxPyrite 0 %.15g\n' ...
    'Brucite 0 %.15g\n' ...
    'Portlandite 0 %.15g\n' ...
    'redoxGypsum 0 %.15g\n' ...
    'END\n' ...
    'USE solution 1\n' ...
    'USE kinetics 1\n' ...
    'USE equilibrium_phases 1\n' ...
    'USE gas_phase 1\n' ...
    '%s'], ...
    buildRates(opt, minBiomass, maxBiomass), ...
    phase.pressureAtm(cellNo), phase.temperature(cellNo) - 273.15, phase.pH(cellNo), ...
    phase.K(cellNo), phase.Na(cellNo), phase.Mg(cellNo), phase.Ca(cellNo), ...
    phase.Cl(cellNo), phase.C4(cellNo), phase.S6(cellNo), phase.S2(cellNo), ...
    phase.Fe3(cellNo), phase.Fe2(cellNo), phase.Si(cellNo), phase.Acetate(cellNo), ...
    phase.pressureAtm(cellNo), phase.temperature(cellNo) - 273.15, ...
    phase.gasVolumeLPerKg(cellNo), ...
    phase.partialH2(cellNo), phase.partialCO2(cellNo), ...
    phase.partialCH4(cellNo), phase.partialH2S(cellNo), phase.partialN2(cellNo), ...
    phase.pressureAtm(cellNo), phase.gasVolumeLPerKg(cellNo), ...
    phase.gasH2(cellNo)./phase.waterMass(cellNo), ...
    phase.gasCH4(cellNo)./phase.waterMass(cellNo), ...
    phase.gasCO2(cellNo)./phase.waterMass(cellNo), ...
    phase.gasH2S(cellNo)./phase.waterMass(cellNo), ...
    phase.gasN2(cellNo)./phase.waterMass(cellNo), ...
    min(biomassSRB, maxBiomass), min(biomassMET, maxBiomass), ...
    min(biomassACE, maxBiomass), ...
    h2Available, h2Available, h2Available, dt, opt.ugfactSteps, ...
    mineral.calcite(cellNo), mineral.dolomite(cellNo), mineral.anhydrite(cellNo), ...
    mineral.quartz(cellNo), mineral.goethite(cellNo), mineral.pyrite(cellNo), ...
    mineral.brucite(cellNo), mineral.portlandite(cellNo), mineral.gypsum(cellNo), ...
    selectedOutputBlock());
end

function rates = buildRates(opt, minBiomass, maxBiomass)
rates = sprintf([ ...
    'RATES\n' ...
    'MET\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_MET")*mol("H2")/(%.15g+mol("H2"))*tot("Carbonate(4)")/(%.15g+tot("Carbonate(4)"))\n' ...
    '30 if (TC<45) then rate = -rate * (TC-10)*(TC+10-2*45)/(45-10)^2\n' ...
    '40 if (TC>=45) then rate = -rate * (TC-122)*(TC+122-2*45)/(45-122)^2\n' ...
    '50 if (-LA("H+")<7.7) then rate = -rate * (-LA("H+")-4.1)*(-LA("H+")+4.1-2*7.7)/(7.7-4.1)^2\n' ...
    '60 if (-LA("H+")>=7.7) then rate = -rate * (-LA("H+")-10.2)*(-LA("H+")+10.2-2*7.7)/(7.7-10.2)^2\n' ...
    '70 if (-LA("H+")>=10.2) then rate = 0\n' ...
    '80 if (-LA("H+")<=4.1) then rate = 0\n' ...
    '90 if (TC<=10) then rate = 0\n' ...
    '100 if (TC>=122) then rate = 0\n' ...
    '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3\n' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,1)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'SRB\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_SRB")*mol("H2")/(%.15g+mol("H2"))*mol("SulfateO4-2")/(%.15g+mol("SulfateO4-2"))\n' ...
    '30 if (TC<48) then rate = -rate * (TC-10)*(TC+10-2*48)/(48-10)^2\n' ...
    '40 if (TC>=48) then rate = -rate * (TC-113)*(TC+113-2*48)/(48-113)^2\n' ...
    '50 if (-LA("H+")<7.01) then rate = -rate * (-LA("H+")-1)*(-LA("H+")+1-2*7.01)/(7.01-1)^2\n' ...
    '60 if (-LA("H+")>=7.01) then rate = -rate * (-LA("H+")-11.5)*(-LA("H+")+11.5-2*7.01)/(7.01-11.5)^2\n' ...
    '70 if (-LA("H+")>=11.5) then rate = 0\n' ...
    '80 if (-LA("H+")<=1) then rate = 0\n' ...
    '90 if (TC<=10) then rate = 0\n' ...
    '100 if (TC>=113) then rate = 0\n' ...
    '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3\n' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,2)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'ACE\n' ...
    '-start\n' ...
    '20 rate = %.15g/86400/%.15g*kin("Biomass_ACE")*mol("H2")/(%.15g+mol("H2"))*tot("Carbonate(4)")/(%.15g+tot("Carbonate(4)"))\n' ...
    '30 if (TC<38) then rate = -rate * (TC-25)*(TC+25-2*38)/(38-25)^2\n' ...
    '40 if (TC>=38) then rate = -rate * (TC-72)*(TC+72-2*38)/(72-38)^2\n' ...
    '50 if (-LA("H+")<7.04) then rate = -rate * (-LA("H+")-3.6)*(-LA("H+")+3.6-2*7.04)/(7.04-3.6)^2\n' ...
    '60 if (-LA("H+")>=7.04) then rate = -rate * (-LA("H+")-9.5)*(-LA("H+")+9.5-2*7.04)/(7.04-9.5)^2\n' ...
    '70 if (-LA("H+")>=9.5) then rate = 0\n' ...
    '80 if (-LA("H+")<=3.6) then rate = 0\n' ...
    '90 if (TC<=25) then rate = 0\n' ...
    '100 if (TC>=72) then rate = 0\n' ...
    '101 TDS = (RHO - TOT("water")/SOLN_VOL)*1e3\n' ...
    '102 if (TDS>=50) then rate = rate * (TDS-2*50+300)*(300-TDS)/(300-50)^2\n' ...
    '103 if (TDS>300) then rate = 0\n' ...
    '110 put(rate,3)\n' ...
    '120 moles = rate*TIME\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_MET\n' ...
    '-start\n' ...
    '20 rate = get(1)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_SRB\n' ...
    '-start\n' ...
    '20 rate = get(2)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n' ...
    'Biomass_ACE\n' ...
    '-start\n' ...
    '20 rate = get(3)\n' ...
    '30 Y = %.15g\n' ...
    '40 b = %.15g/86400\n' ...
    '50 rate = Y*rate-b*M\n' ...
    '60 moles = -rate*TIME\n' ...
    '70 N = (M-moles)*%.15g\n' ...
    '80 if (M-moles)<%.15g then moles = M-%.15g\n' ...
    '90 if (N>=%.15g) then moles = M-%.15g\n' ...
    '200 SAVE moles\n' ...
    '-end\n'], ...
    opt.ugfactMuMET, opt.ugfactYMET, opt.ugfactKDMET, opt.ugfactKAMET, ...
    opt.ugfactMuSRB, opt.ugfactYSRB, opt.ugfactKDSRB, opt.ugfactKASRB, ...
    opt.ugfactMuACE, opt.ugfactYACE, opt.ugfactKDACE, opt.ugfactKAACE, ...
    opt.ugfactYMET, opt.ugfactBMET, opt.ugfactBiomassMW/opt.ugfactCellMass, ...
    minBiomass, minBiomass, opt.ugfactNmax, maxBiomass, ...
    opt.ugfactYSRB, opt.ugfactBSRB, opt.ugfactBiomassMW/opt.ugfactCellMass, ...
    minBiomass, minBiomass, opt.ugfactNmax, maxBiomass, ...
    opt.ugfactYACE, opt.ugfactBACE, opt.ugfactBiomassMW/opt.ugfactCellMass, ...
    minBiomass, minBiomass, opt.ugfactNmax, maxBiomass);
end

function block = selectedOutputBlock()
% Keep the UGFACT selected-output order and custom pseudo-species intact.
block = sprintf([ ...
    'USER_PUNCH\n' ...
    '-headings MET_RATE ACE_RATE SRB_RATE TDS CO3-2 HCO3- TOT_CO2 Dissolved_CO2 Z_Factor act("Ca+2") act("CO3-2") act(CaHCO3+) Ca+2 CaHCO3+\n' ...
    '-start\n' ...
    '20 rate1 = get(1)\n' ...
    '30 Punch rate1\n' ...
    '40 rate2 = get(3)\n' ...
    '50 Punch rate2\n' ...
    '60 rate3 = get(2)\n' ...
    '70 Punch rate3\n' ...
    '80 Punch (RHO - TOT("water")/SOLN_VOL)*1e3\n' ...
    '90 Punch MOL("CarbonateO3-2")\n' ...
    '91 Punch MOL("HCarbonateO3-")\n' ...
    '92 Punch GAS("redoxCarbonateO2(g)") + MOL("CarbonateO2")\n' ...
    '93 Punch TOT("Carbonate(4)") - MOL("CarbonateO3-2") - MOL("HCarbonateO3-") - MOL("CaHCarbonateO3+")\n' ...
    '94 Punch GAS_P*GAS_VM/TK/0.082057366080960\n' ...
    '95 Punch act("Ca+2")\n' ...
    '96 Punch act("CarbonateO3-2")\n' ...
    '97 Punch act("CaHCarbonateO3+")\n' ...
    '98 Punch mol("Ca+2")\n' ...
    '99 Punch mol("CaHCarbonateO3+")\n' ...
    '-end\n' ...
    'SELECTED_OUTPUT\n' ...
    '-sim false\n' ...
    '-step true\n' ...
    '-soln false\n' ...
    '-pH true\n' ...
    '-molalities H2 N2 CarbonateO2 MethaneH4 H2Sulfide\n' ...
    '-state false\n' ...
    '-water true\n' ...
    '-time true\n' ...
    '-gases H2(g) redoxCarbonateO2(g) redoxCH4(g) redoxH2S(g) N2(g)\n' ...
    '-distance false\n' ...
    '-equilibrium_phases redoxCalcite redoxAnhydrite redoxGypsum redoxDolomite redoxGoethite redoxPyrite Brucite Portlandite Quartz\n' ...
    '-kinetic_reactants Biomass_SRB Biomass_MET Biomass_ACE\n' ...
    '-total Carbonate(4) Sulfate(6) Ca Mg Fe_di Fe_tri K Na Cl Acetate Sulfide(-2) Si\n' ...
    '-saturation_indices redoxCalcite Brucite Portlandite redoxAnhydrite redoxDolomite Quartz redoxH2S(g)\n' ...
    'END\n']);
end

function output = runIPhreeqcCOM(input, opt, cellNo)
try
    iph = actxserver(char(opt.comProgId));
catch ME
    error('H2Biochem:UGFACTCOMActivation', ...
        'IPhreeqcCOM activation failed in cell %d for "%s":\n%s', ...
        cellNo, char(opt.comProgId), ME.message);
end
try
    loadStatus = iph.LoadDatabase(char(opt.databaseFile));
    if loadStatus ~= 0
        error('H2Biochem:UGFACTCOMDatabase', ...
            'PHREEQC database load failed in cell %d:\n%s', cellNo, ...
            getPhreeqcError(iph));
    end
    status = iph.RunString(input);
    if status ~= 0
        error('H2Biochem:UGFACTCOMRun', ...
            'PHREEQC failed in cell %d:\n%s', cellNo, getPhreeqcError(iph));
    end
    output = iph.GetSelectedOutputArray;
    if isempty(output)
        error('H2Biochem:UGFACTCOMOutput', ...
            'PHREEQC returned no selected output in cell %d:\n%s', ...
            cellNo, getPhreeqcError(iph));
    end
catch ME
    phreeqcMessage = getPhreeqcError(iph);
    try
        clear iph
    catch
    end
    if startsWith(ME.identifier, 'H2Biochem:UGFACTCOM')
        rethrow(ME);
    end
    error('H2Biochem:UGFACTCOMRun', ...
        'IPhreeqcCOM failed in cell %d:\n%s\nPHREEQC message:\n%s', ...
        cellNo, ME.message, phreeqcMessage);
end
clear iph
end

function message = getPhreeqcError(iph)
try
    message = char(iph.GetErrorString());
catch
    message = 'No PHREEQC error string was available from IPhreeqcCOM.';
end
if isempty(strtrim(message))
    message = 'IPhreeqcCOM did not provide an error message.';
end
end

function result = parseSelectedOutput(raw, cellNo)
assert(iscell(raw) && size(raw, 1) >= 2 && size(raw, 2) >= 1, ...
    ['PHREEQC selected output in cell %d does not follow the required ', ...
     'UGFACT GetSelectedOutputArray schema.'], cellNo);
headers = normalizeHeaders(raw(1, :));
values = selectedOutputValues(raw(2:end, :), cellNo);
assert(all(isfinite(values(:))), ...
    'PHREEQC selected output contains non-finite values in cell %d.', cellNo);

result = emptyResult();
result.pH = finalValue(values, headers, {'ph'}, cellNo);
% IPhreeqcCOM versions differ in whether selected molality headers retain
% PHREEQC's "m_" prefix. Accept both representations of the unchanged
% UGFACT selected-output schema.
result.aqH2 = finalValue(values, headers, {'mh2', 'mh2molkgw', 'h2'}, cellNo);
result.aqN2 = finalValue(values, headers, {'mn2', 'mn2molkgw', 'n2'}, cellNo);
result.aqCO2 = finalValue(values, headers, ...
    {'mcarbonateo2', 'mcarbonateo2molkgw', 'carbonateo2'}, cellNo);
result.aqCH4 = finalValue(values, ...
    headers, {'mmethaneh4', 'mmethaneh4molkgw', 'methaneh4'}, cellNo);
result.aqH2S = finalValue(values, ...
    headers, {'mh2sulfide', 'mh2sulfidemolkgw', 'h2sulfide'}, cellNo);
result.water = finalValue(values, headers, {'water', 'massh2o'}, cellNo);
result.gasH2 = finalValue(values, headers, {'gh2g', 'h2g'}, cellNo);
result.gasCO2 = finalValue(values, headers, ...
    {'gredoxcarbonateo2g', 'redoxcarbonateo2g'}, cellNo);
result.gasCH4 = finalValue(values, headers, {'gredoxch4g', 'redoxch4g'}, cellNo);
result.gasH2S = finalValue(values, headers, {'gredoxh2sg', 'redoxh2sg'}, cellNo);
result.gasN2 = finalValue(values, headers, {'gn2g', 'n2g'}, cellNo);
result.calcite = finalValue(values, headers, {'redoxcalcite'}, cellNo);
result.anhydrite = finalValue(values, headers, {'redoxanhydrite'}, cellNo);
result.gypsum = finalValue(values, headers, {'redoxgypsum'}, cellNo);
result.dolomite = finalValue(values, headers, {'redoxdolomite'}, cellNo);
result.goethite = finalValue(values, headers, {'redoxgoethite'}, cellNo);
result.pyrite = finalValue(values, headers, {'redoxpyrite'}, cellNo);
result.brucite = finalValue(values, headers, {'brucite'}, cellNo);
result.portlandite = finalValue(values, headers, {'portlandite'}, cellNo);
result.quartz = finalValue(values, headers, {'quartz'}, cellNo);
result.biomassSRB = finalValue(values, headers, {'kbiomasssrb', 'biomasssrb'}, cellNo);
result.biomassMET = finalValue(values, headers, {'kbiomassmet', 'biomassmet'}, cellNo);
result.biomassACE = finalValue(values, headers, {'kbiomassace', 'biomassace'}, cellNo);
result.totalCarbon = finalValue(values, headers, ...
    {'carbonate4', 'carbonate4molkgw'}, cellNo);
result.sulfate = finalValue(values, headers, ...
    {'sulfate6', 'sulfate6molkgw'}, cellNo);
result.ca = finalValue(values, headers, {'ca', 'camolkgw'}, cellNo);
result.mg = finalValue(values, headers, {'mg', 'mgmolkgw'}, cellNo);
result.acetate = finalValue(values, headers, ...
    {'acetate', 'acetatemolkgw'}, cellNo);
result.sulfide = finalValue(values, headers, ...
    {'sulfide2', 'sulfide2molkgw'}, cellNo);
result.hco3 = finalValue(values, headers, {'hco3'}, cellNo);

time = selectedValue(values, headers, {'time'}, cellNo);
result.rateMET = timeAverage(time, selectedValue(values, headers, {'metrate'}, cellNo));
result.rateACE = timeAverage(time, selectedValue(values, headers, {'acerate'}, cellNo));
result.rateSRB = timeAverage(time, selectedValue(values, headers, {'srbrate'}, cellNo));
end

function headers = normalizeHeaders(headers)
headers = cellfun(@(x) lower(regexprep(char(x), '[^a-zA-Z0-9]', '')), ...
    headers, 'UniformOutput', false);
end

function values = selectedOutputValues(raw, cellNo)
values = zeros(size(raw));
for i = 1:numel(raw)
    valueAt = raw{i};
    if ischar(valueAt) || (isstring(valueAt) && isscalar(valueAt))
        valueAt = str2double(valueAt);
    end
    if ~isnumeric(valueAt) || ~isscalar(valueAt)
        error('H2Biochem:UGFACTCOMOutput', ...
            'PHREEQC selected output contains a nonnumeric entry in cell %d.', cellNo);
    end
    values(i) = valueAt;
end
end

function value = finalValue(values, headers, aliases, cellNo)
value = selectedValue(values, headers, aliases, cellNo);
value = value(end);
end

function values = selectedValue(values, headers, aliases, cellNo)
column = find(ismember(headers, aliases), 1);
assert(~isempty(column), ...
    ['PHREEQC selected output in cell %d is missing required UGFACT ', ...
     'column "%s". Available columns: %s'], ...
    cellNo, aliases{1}, strjoin(headers, ', '));
values = values(:, column);
end

function average = timeAverage(time, rate)
if numel(time) < 2 || time(end) <= time(1)
    average = rate(end);
    return;
end
average = sum(0.5*(rate(1:end-1) + rate(2:end)).*diff(time))./ ...
    (time(end) - time(1));
end

function state = updateStateFromResults(model, state, opt, phase, mineral, result, waterMass, dt) %#ok<INUSD>
nc = model.G.cells.num;
rhoWater = opt.waterDensity;
result = result(:);
stateBefore = state;
inactive = ~phase.activeCells;

state.phreeqcPH = reshape([result.pH], [], 1);
state.phreeqcHCO3Molality = max(reshape([result.hco3], [], 1), 0);
state.phreeqcCO2Molality = max(reshape([result.aqCO2], [], 1), 0);
state.phreeqcTotalCarbon = max(reshape([result.totalCarbon], [], 1), 0);
state.tracerHCO3 = max(state.phreeqcTotalCarbon - state.phreeqcCO2Molality, 0).*rhoWater;
state.tracerSO4 = max(reshape([result.sulfate], [], 1), 0).*rhoWater;
state.tracerHS = max(reshape([result.sulfide], [], 1), 0).*rhoWater;
state.tracerCa = max(reshape([result.ca], [], 1), 0).*rhoWater;
state.tracerMg = max(reshape([result.mg], [], 1), 0).*rhoWater;
state.phreeqcUgfactAcetate = max(reshape([result.acetate], [], 1), 0);

pka = state.phreeqcPH - log10(state.phreeqcHCO3Molality./ ...
    max(state.phreeqcCO2Molality, 1e-30));
previousPka = getStateVector(state, 'phreeqcCarbonatePka1', nc, ...
    model.carbonateBufferPka1);
pka(~isfinite(pka)) = previousPka(~isfinite(pka));
state.phreeqcCarbonatePka1 = pka;

state.phreeqcMineralCalcite = max(reshape([result.calcite], [], 1), 0).*waterMass;
state.phreeqcMineralDolomite = max(reshape([result.dolomite], [], 1), 0).*waterMass;
state.phreeqcMineralAnhydrite = max(reshape([result.anhydrite], [], 1), 0).*waterMass;
state.phreeqcMineralQuartz = max(reshape([result.quartz], [], 1), 0).*waterMass;
state.phreeqcMineralGoethite = max(reshape([result.goethite], [], 1), 0).*waterMass;
state.phreeqcMineralBrucite = max(reshape([result.brucite], [], 1), 0).*waterMass;
state.phreeqcMineralPortlandite = max(reshape([result.portlandite], [], 1), 0).*waterMass;
state.phreeqcMineralPyrite = max(reshape([result.pyrite], [], 1), 0).*waterMass;
state.phreeqcMineralGypsum = max(reshape([result.gypsum], [], 1), 0).*waterMass;

biomassMET = max(reshape([result.biomassMET], [], 1), 0);
biomassACE = max(reshape([result.biomassACE], [], 1), 0);
biomassSRB = max(reshape([result.biomassSRB], [], 1), 0);
biomassMET(inactive) = state.phreeqcUgfactBiomassMET(inactive);
biomassACE(inactive) = state.phreeqcUgfactBiomassACE(inactive);
biomassSRB(inactive) = state.phreeqcUgfactBiomassSRB(inactive);
state.phreeqcUgfactBiomassMET = biomassMET;
state.phreeqcUgfactBiomassACE = biomassACE;
state.phreeqcUgfactBiomassSRB = biomassSRB;
reactionRates = [reshape([result.rateMET], [], 1), ...
    reshape([result.rateACE], [], 1), reshape([result.rateSRB], [], 1)];
reactionRates(inactive, :) = 0;
state.phreeqcUgfactReactionRates = reactionRates;
state.phreeqcUgfactActiveCells = phase.activeCells;
state.phreeqcUgfactH2ConsumptionByReactionRate = reactionRates.*waterMass;
state.phreeqcUgfactH2ConsumptionByReactionMoles = ...
    state.phreeqcUgfactH2ConsumptionByReactionRate.*dt;
state.phreeqcUgfactH2ConsumptionRate = sum(reactionRates, 2).*waterMass;
state.phreeqcUgfactH2ConsumptionMoles = ...
    state.phreeqcUgfactH2ConsumptionRate.*dt;
state.h2ConsumptionRate = reactionRates.*waterMass;
state = restoreInactiveChemistry(state, stateBefore, inactive);

componentMoles = phase.componentMoles;
names = model.EOSModel.CompositionalMixture.names;
waterIndex = findComponent(names, {'H2O', 'Water'});
assert(~isempty(waterIndex), 'UGFACT PHREEQC requires the EOS H2O component.');
waterMolarMass = model.EOSModel.CompositionalMixture.molarMass(waterIndex);
componentMoles(:, waterIndex) = max(componentMoles(:, waterIndex) + ...
    (reshape([result.water], [], 1) - 1).*waterMass./waterMolarMass, 0);
componentMoles = replaceComponentMoles(componentMoles, names, {'H2', 'Hydrogen'}, ...
    (reshape([result.gasH2], [], 1) + reshape([result.aqH2], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'CO2', 'CarbonDioxide'}, ...
    (reshape([result.gasCO2], [], 1) + reshape([result.aqCO2], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'C1', 'CH4', 'Methane'}, ...
    (reshape([result.gasCH4], [], 1) + reshape([result.aqCH4], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'H2S', 'HydrogenSulfide'}, ...
    (reshape([result.gasH2S], [], 1) + reshape([result.aqH2S], [], 1)).*waterMass, true);
componentMoles = replaceComponentMoles(componentMoles, names, {'N2', 'Nitrogen'}, ...
    (reshape([result.gasN2], [], 1) + reshape([result.aqN2], [], 1)).*waterMass, false);
componentMoles = replaceComponentMoles(componentMoles, names, ...
    {'CH3COOH', 'AceticAcid', 'Acetate'}, ...
    max(reshape([result.acetate], [], 1), 0).*waterMass, false);
componentMoles(inactive, :) = phase.componentMoles(inactive, :);
assert(all(isfinite(componentMoles(:)) & componentMoles(:) >= 0), ...
    'UGFACT PHREEQC returned invalid EOS component inventories.');

totalMoles = sum(componentMoles, 2);
assert(all(isfinite(totalMoles) & totalMoles > 0), ...
    'UGFACT PHREEQC produced invalid total EOS inventory.');
state.components = bsxfun(@rdivide, componentMoles, totalMoles);
assert(all(abs(sum(state.components, 2) - 1) < 100*eps), ...
    'UGFACT PHREEQC produced EOS compositions that do not sum to one.');

state = clearStateFunctionCaches(model, state);
model = updateEOSSalinityForReflash(model, state);
state = model.computeFlash(state, inf);
state = refreshOutputStateFunctions(model, state);
end

function state = restoreInactiveChemistry(state, stateBefore, inactive)
fields = {'phreeqcPH', 'phreeqcHCO3Molality', 'phreeqcCO2Molality', ...
    'phreeqcTotalCarbon', 'tracerHCO3', 'tracerSO4', 'tracerHS', ...
    'tracerCa', 'tracerMg', 'phreeqcUgfactAcetate', 'phreeqcCarbonatePka1', ...
    'phreeqcMineralCalcite', 'phreeqcMineralDolomite', ...
    'phreeqcMineralAnhydrite', 'phreeqcMineralQuartz', ...
    'phreeqcMineralGoethite', 'phreeqcMineralBrucite', ...
    'phreeqcMineralPortlandite', 'phreeqcMineralPyrite', ...
    'phreeqcMineralGypsum'};
for i = 1:numel(fields)
    field = fields{i};
    if isfield(stateBefore, field)
        state.(field)(inactive, :) = stateBefore.(field)(inactive, :);
    end
end
end

function componentMoles = replaceComponentMoles(componentMoles, names, aliases, values, required)
index = findComponent(names, aliases);
if isempty(index)
    assert(~required, 'UGFACT PHREEQC requires EOS component %s.', aliases{1});
    return;
end
componentMoles(:, index) = max(values, 0);
end

function [rhoL, rhoV, sL, sV] = getPhaseProperties(model, state)
nc = model.G.cells.num;
s = value(state.s);
liquid = model.getLiquidIndex();
vapor = model.getVaporIndex();
if iscell(s)
    sL = s{liquid};
    sV = s{vapor};
else
    sL = s(:, liquid);
    sV = s(:, vapor);
end
propmodel = model.EOSModel.PropertyModel;
rhoL = propmodel.computeMolarDensity(model.EOSModel, value(state.pressure), ...
    value(state.x), value(state.Z_L), value(state.T), true);
rhoV = propmodel.computeMolarDensity(model.EOSModel, value(state.pressure), ...
    value(state.y), value(state.Z_V), value(state.T), false);
rhoL = asCellVector(value(rhoL), nc, 'liquid molar density');
rhoV = asCellVector(value(rhoV), nc, 'gas molar density');
sL = asCellVector(sL, nc, 'liquid saturation');
sV = asCellVector(sV, nc, 'gas saturation');
end

function componentMoles = getEOSComponentMoles(model, state)
nc = model.G.cells.num;
poreVolume = asCellVector(value(model.PVTPropertyFunctions.get( ...
    model, state, 'PoreVolume')), nc, 'pore volume');
[rhoL, rhoV, sL, sV] = getPhaseProperties(model, state);
totalMoles = poreVolume.*(sL.*rhoL + sV.*rhoV);
assert(all(isfinite(totalMoles) & totalMoles > 0), ...
    'UGFACT PHREEQC coupling requires positive EOS moles per cell.');
components = value(state.components);
assert(ismatrix(components) && size(components, 1) == nc && ...
    size(components, 2) == model.EOSModel.getNumberOfComponents(), ...
    'EOS components must be a cell-by-component matrix.');
componentMoles = bsxfun(@times, totalMoles, components);
end

function [x, rhoMolarL] = getLiquidCompositionAndDensity(model, state)
x = value(state.x);
if iscell(x)
    x = horzcat(x{:});
end
rhoMolarL = model.EOSModel.PropertyModel.computeMolarDensity(model.EOSModel, ...
    value(state.pressure), value(state.x), value(state.Z_L), value(state.T), true);
rhoMolarL = value(rhoMolarL);
end

function moles = getComponentMoles(componentMoles, names, aliases, required)
if nargin < 4
    required = true;
end
index = findComponent(names, aliases);
if isempty(index)
    assert(~required, 'UGFACT PHREEQC requires EOS component %s.', aliases{1});
    moles = zeros(size(componentMoles, 1), 1);
    return;
end
moles = componentMoles(:, index);
end

function molality = getAqueousMolality(x, rhoMolarL, names, aliases, required)
if nargin < 5
    required = true;
end
index = findComponent(names, aliases);
if isempty(index)
    assert(~required, 'UGFACT PHREEQC requires EOS component %s.', aliases{1});
    molality = zeros(size(rhoMolarL));
    return;
end
molality = max(rhoMolarL.*x(:, index)./1000, 0);
end

function moles = zeroTraceComponent(moles, components, names, aliases)
index = findComponent(names, aliases);
if ~isempty(index)
    moles(components(:, index) <= 1e-8) = 0;
end
end

function pressure = gasPartialPressure(moles, phase)
% UGFACT supplies PHREEQC with p_i = Z_v*n_i*R*T/V_g (atm).
pressure = phase.ZV.*moles.*0.082057366080960.*phase.gasTemperature./ ...
    phase.gasVolumeL;
end

function state = clearStateFunctionCaches(model, state)
groups = model.getStateFunctionGroupings();
for i = 1:numel(groups)
    name = groups{i}.getStateFunctionContainerName();
    if isfield(state, name)
        state = rmfield(state, name);
    end
end
end

function state = refreshOutputStateFunctions(model, state)
outputs = unique(model.OutputStateFunctions, 'stable');
for i = 1:numel(outputs)
    [~, state] = model.getProp(state, outputs{i});
end
end

function model = updateEOSSalinityForReflash(model, state)
if model.sulfateReduction && isa(model.EOSModel, 'SoreideWhitsonEos')
    assert(isfield(state, 'tracerHS') && isfield(state, 'h2sDissolvedLag'), ...
        'UGFACT PHREEQC reflash requires HS and lagged dissolved-H2S state.');
    model.EOSModel = model.EOSModel.enablesrb_coupling( ...
        value(state.tracerSO4), value(state.tracerHS), ...
        value(state.tracerHS) + value(state.h2sDissolvedLag), value(state.T));
end
end

function waterMass = getWaterMass(model, state, rhoWater) %#ok<INUSD>
poreVolume = value(model.PVTPropertyFunctions.get(model, state, 'PoreVolume'));
s = value(state.s);
liquid = model.getLiquidIndex();
if iscell(s)
    sL = s{liquid};
else
    sL = s(:, liquid);
end
names = model.EOSModel.CompositionalMixture.names;
waterIndex = findComponent(names, {'H2O', 'Water'});
assert(~isempty(waterIndex), 'UGFACT PHREEQC requires an EOS H2O component.');
[x, rhoMolarL] = getLiquidCompositionAndDensity(model, state);
waterMass = poreVolume.*max(sL, 1e-12).*rhoMolarL.* ...
    max(x(:, waterIndex), 0).*model.EOSModel.CompositionalMixture.molarMass(waterIndex);
assert(all(isfinite(waterMass) & waterMass > 0), ...
    'UGFACT PHREEQC coupling requires positive liquid water mass.');
end

function values = getStateVector(state, field, nc, default)
if isfield(state, field)
    values = value(state.(field));
else
    values = default;
end
values = asCellVector(values, nc, field);
end

function values = optionVector(options, field, default, nc)
if isfield(options, field)
    values = options.(field);
else
    values = default;
end
values = asCellVector(values, nc, field);
end

function values = asCellVector(values, nc, name)
if isscalar(values)
    values = repmat(values, nc, 1);
else
    values = values(:);
    assert(numel(values) == nc, ...
        'UGFACT PHREEQC expected %d %s values, got %d.', nc, name, numel(values));
end
end

function index = findComponent(names, aliases)
index = [];
for i = 1:numel(aliases)
    index = find(strcmpi(names, aliases{i}), 1);
    if ~isempty(index)
        return;
    end
end
end

function result = emptyResult()
result = struct( ...
    'pH', 0, 'aqH2', 0, 'aqN2', 0, 'aqCO2', 0, 'aqCH4', 0, 'aqH2S', 0, ...
    'water', 0, 'gasH2', 0, 'gasCO2', 0, 'gasCH4', 0, 'gasH2S', 0, ...
    'gasN2', 0, 'calcite', 0, 'anhydrite', 0, 'gypsum', 0, 'dolomite', 0, ...
    'goethite', 0, 'pyrite', 0, 'brucite', 0, 'portlandite', 0, 'quartz', 0, ...
    'biomassSRB', 0, 'biomassMET', 0, 'biomassACE', 0, 'totalCarbon', 0, ...
    'sulfate', 0, 'ca', 0, 'mg', 0, 'acetate', 0, 'sulfide', 0, 'hco3', 0, ...
    'rateMET', 0, 'rateACE', 0, 'rateSRB', 0);
end

function isAbsolute = isAbsolutePath(path)
path = char(path);
isAbsolute = ~isempty(regexp(path, '^[A-Za-z]:[\\/]|^\\\\', 'once')) || ...
    startsWith(path, filesep);
end
