function scenarios = testAllDiffusionEffects(varargin)
% Compare all simulation methods and optionally test transport effects.
%
% SYNOPSIS:
%   scenarios = testAllDiffusionEffects('phreeqcDatabaseFile', databaseFile)
%   scenarios = testAllDiffusionEffects( ...
%       'phreeqcDatabaseFile', databaseFile, ...
%       'runDiffusionEffects', true)
%
% If phreeqcDatabaseFile is omitted, the function checks the
% PHREEQC_DATABASE_FILE environment variable and then the MATLAB path.
%
% The first three scenarios always compare:
%   1. Original h2-biochem model
%   2. Sequential compositional PHREEQC
%   3. Sequential h2-biochem PHREEQC
%
% The optional transport matrix runs with the original model and sequential
% h2-biochem PHREEQC. Sequential compositional PHREEQC owns separate local
% PHREEQC biomass and therefore rejects microbial diffusion and chemotaxis.

    mrstModule add ad-props compositional h2-biochem

    opt = struct( ...
        'phreeqcDatabaseFile', '', ...
        'runDiffusionEffects', false);
    opt = merge_options(opt, varargin{:});

    assert(ischar(opt.phreeqcDatabaseFile) || ...
        (isstring(opt.phreeqcDatabaseFile) && isscalar(opt.phreeqcDatabaseFile)), ...
        'phreeqcDatabaseFile must be a character vector or scalar string.');
    opt.phreeqcDatabaseFile = resolvePhreeqcDatabaseFile( ...
        char(opt.phreeqcDatabaseFile));
    validateattributes(opt.runDiffusionEffects, {'logical', 'numeric'}, ...
        {'scalar', 'real', 'finite'}, mfilename, 'runDiffusionEffects');
    opt.runDiffusionEffects = logical(opt.runDiffusionEffects);

    commonOptions = { ...
        'injectionCO2', 0, ...
        'bacteriamodel', true, ...
        'bactDiffusion', false, ...
        'chemotaxisEffect', false, ...
        'molecularDiffusion', false, ...
        'molecularDispersion', false, ...
        'bioClogging', false};

    methodCases = { ...
        struct( ...
            'name', 'Original h2-biochem', ...
            'setupOptions', {{ ...
                %'carbonateBufferPH', 5.96, ...
                %'initialHCO3', 5.001e-2, ...
                'carbonateBuffer', true, ...
                'equilibrateInitialCO2', true,...
                'phreeqcTimestepCoupling', false}}, ...
            'useSequentialDriver', false, ...
            'expectedClass', 'BiochemistryModel', ...
            'expectedBackend', ''), ...
        struct( ...
            'name', 'Sequential compositional PHREEQC', ...
            'setupOptions', {{ ...
                'carbonateBuffer', true, ...
                'phreeqcTimestepCoupling', true, ...
                'phreeqcBackend', 'sequential-compositional-phreeqc', ...
                'phreeqcDatabaseFile', opt.phreeqcDatabaseFile}}, ...
            'useSequentialDriver', false, ...
            'expectedClass', 'BiochemistryPhreeqcModel', ...
            'expectedBackend', 'sequential-compositional-phreeqc'), ...
        struct( ...
            'name', 'Sequential h2-biochem PHREEQC', ...
            'setupOptions', {{ ...
                'carbonateBuffer', true, ...
                'paperBiomassKinetics', true,...
                'phreeqcTimestepCoupling', true, ...
                'phreeqcPicardAdaptiveRelaxation', true, ...
                'phreeqcPicardMaxIterations', 15, ...
                'phreeqcPicardMinimumRelaxation', 0.4, ...
                'phreeqcPicardFailOnNonconvergence', true, ...
                'phreeqcPicardRelaxation', 0.75, ...
                'phreeqcPicardRelativeTolerance', 5e-2, ...
                'phreeqcPicardReactionRelativeTolerance', 5e-2, ...
                'phreeqcPicardPHTolerance', 2e-2, ...
                'phreeqcPicardPkaTolerance', 2e-2, ...
                'phreeqcPicardCutTimestepOnNonconvergence', true, ...
                'phreeqcPicardMaxTimestepCuts', 2, ...
                'phreeqcBackend', 'sequential-h2biochem-phreeqc', ...
                'phreeqcDatabaseFile', opt.phreeqcDatabaseFile}}, ...
            'useSequentialDriver', true, ...
            'expectedClass', 'BiochemistryPhreeqcModel', ...
            'expectedBackend', 'sequential-h2biochem-phreeqc')};

    fprintf('\n===== Comparing h2-biochem simulation methods =====\n\n');
    scenarios = cell(1, numel(methodCases));
    for i = 2:numel(methodCases)
        method = methodCases{i};
        fprintf('Method %d/%d: %s\n', i, numel(methodCases), method.name);
        scenarios{i} = runScenario(method.name, ...
            [commonOptions, method.setupOptions], method.useSequentialDriver, ...
            method.expectedClass, method.expectedBackend);
    end

    if opt.runDiffusionEffects
        scenarios = runOptionalDiffusionEffects( ...
            scenarios, commonOptions, methodCases, opt.phreeqcDatabaseFile);
    end

    fprintf('\nCompleted %d simulation scenarios successfully.\n', numel(scenarios));
end

function databaseFile = resolvePhreeqcDatabaseFile(databaseFile)
    if isempty(strtrim(databaseFile))
        databaseFile = getenv('PHREEQC_DATABASE_FILE');
    end
    if isempty(strtrim(databaseFile))
        databaseFile = which('PHREEQC_Modified.DAT');
    end
    if isempty(strtrim(databaseFile))
        error('testAllDiffusionEffects:MissingPhreeqcDatabase', ...
            ['Testing all three methods requires PHREEQC_Modified.DAT. ', ...
             'Pass ''phreeqcDatabaseFile'', databaseFile or set the ', ...
             'PHREEQC_DATABASE_FILE environment variable.']);
    end
    if ~isfile(databaseFile)
        error('testAllDiffusionEffects:PhreeqcDatabaseNotFound', ...
            ['PHREEQC_Modified.DAT was not found at:\n  %s\n', ...
             'Pass the actual absolute file path instead of the ', ...
             'documentation placeholder.'], databaseFile);
    end
    isAbsolute = ~isempty(regexp(databaseFile, ...
        '^[A-Za-z]:[\\/]|^\\\\', 'once')) || startsWith(databaseFile, filesep);
    assert(isAbsolute, ...
        'phreeqcDatabaseFile must be an absolute path; got %s.', databaseFile);
    [~, name, extension] = fileparts(databaseFile);
    assert(strcmpi([name, extension], 'PHREEQC_Modified.DAT'), ...
        ['phreeqcDatabaseFile must point to PHREEQC_Modified.DAT; ', ...
         'got %s.'], databaseFile);
end

function scenario = runScenario( ...
        name, setupOptions, useSequentialDriver, expectedClass, expectedBackend)
    [biochemFluid, model, schedule, state0] = ...
        setupH2StorageExampleWithSRB_benchmark(setupOptions{:});
%    assert(strcmp(class(model), expectedClass), ...
%        'Scenario "%s" constructed %s instead of %s.', ...
%        name, class(model), expectedClass);
    if ~isempty(expectedBackend)
        assert(strcmp(model.phreeqcBackend, expectedBackend), ...
            'Scenario "%s" selected the wrong PHREEQC backend.', name);
    end

    fprintf('  Running simulation...');
    if useSequentialDriver
        [ws, states, report] = simulateSequentialH2BiochemPhreeqc( ...
            state0, model, schedule);
    else
        [ws, states, report] = simulateScheduleAD(state0, model, schedule);
    end
    fprintf(' OK\n');

    scenario = struct( ...
        'name', name, ...
        'biochemFluid', biochemFluid, ...
        'model', model, ...
        'schedule', schedule, ...
        'state0', state0, ...
        'states', {states}, ...
        'ws', {ws}, ...
        'report', report);
end

function scenarios = runOptionalDiffusionEffects( ...
        scenarios, commonOptions, methodCases, databaseFile)
    fprintf('\n===== Testing optional diffusion and transport effects =====\n\n');

    effectCases = { ...
        struct('name', 'Microbial diffusion', ...
            'options', {{'bactDiffusion', true}}), ...
        struct('name', 'Chemotaxis', ...
            'options', {{'chemotaxisEffect', true}}), ...
        struct('name', 'Microbial diffusion + chemotaxis', ...
            'options', {{'bactDiffusion', true, 'chemotaxisEffect', true}}), ...
        struct('name', 'Molecular diffusion', ...
            'options', {{'molecularDiffusion', true}}), ...
        struct('name', 'Mechanical dispersion', ...
            'options', {{'molecularDispersion', true}}), ...
        struct('name', 'Molecular diffusion + dispersion', ...
            'options', {{ ...
                'molecularDiffusion', true, ...
                'molecularDispersion', true}}), ...
        struct('name', 'All transport effects', ...
            'options', {{ ...
                'bactDiffusion', true, ...
                'chemotaxisEffect', true, ...
                'molecularDiffusion', true, ...
                'molecularDispersion', true}}), ...
        struct('name', 'All transport effects + bio-clogging', ...
            'options', {{ ...
                'bactDiffusion', true, ...
                'chemotaxisEffect', true, ...
                'molecularDiffusion', true, ...
                'molecularDispersion', true, ...
                'bioClogging', true}})};

    % The original and sequential h2-biochem methods retain MRST biomass,
    % so both can exercise microbial transport.
    supportedMethods = methodCases([1, 3]);
    for m = 1:numel(supportedMethods)
        method = supportedMethods{m};
        for e = 1:numel(effectCases)
            effect = effectCases{e};
            name = sprintf('%s: %s', method.name, effect.name);
            fprintf('%s\n', name);
            setupOptions = overrideOptions( ...
                [commonOptions, method.setupOptions], effect.options);
            scenarios{end + 1} = runScenario( ... %#ok<AGROW>
                name, setupOptions, method.useSequentialDriver, ...
                method.expectedClass, method.expectedBackend);
        end
    end

    assertSequentialCompositionalRejectsMicrobialTransport( ...
        commonOptions, databaseFile);
end

function assertSequentialCompositionalRejectsMicrobialTransport( ...
        commonOptions, databaseFile)
    setupOptions = overrideOptions(commonOptions, { ...
        'bactDiffusion', true, ...
        'carbonateBuffer', true, ...
        'phreeqcTimestepCoupling', true, ...
        'phreeqcBackend', 'sequential-compositional-phreeqc', ...
        'phreeqcDatabaseFile', databaseFile});

    rejected = false;
    try
        setupH2StorageExampleWithSRB_benchmark(setupOptions{:});
    catch exception
        rejected = contains(exception.message, ...
            'cannot be combined with bactDiffusion or chemotaxisEffect');
        if ~rejected
            rethrow(exception);
        end
    end
    assert(rejected, ...
        ['Sequential compositional PHREEQC unexpectedly accepted microbial ', ...
         'diffusion.']);
    fprintf(['Sequential compositional PHREEQC correctly rejected microbial ', ...
        'diffusion.\n']);
end

function options = overrideOptions(options, replacements)
    assert(mod(numel(options), 2) == 0 && mod(numel(replacements), 2) == 0, ...
        'Options must be property/value pairs.');
    for i = 1:2:numel(replacements)
        index = find(strcmpi(options(1:2:end), replacements{i}), 1);
        if isempty(index)
            options(end + 1:end + 2) = replacements(i:i + 1);
        else
            options{2*index} = replacements{i + 1};
        end
    end
end

%{
Copyright 2009-2026 SINTEF Digital, Mathematics & Cybernetics.

This file is part of The MATLAB Reservoir Simulation Toolbox (MRST).

MRST is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

MRST is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with MRST.  If not, see <http://www.gnu.org/licenses/>.
%}
